name = "kaiser-database-archive-runner"
main = "workers/database-archive-runner.js"
compatibility_date = "2026-06-26"
workers_dev = true

[[d1_databases]]
binding = "SMART_ODPADY_DB"
database_name = "smart-odpady"
database_id = "6d9ab099-fa10-4245-b06b-e146b63450a9"

[[d1_databases]]
binding = "DB_ARCHIVE"
database_name = "SMART_ODPADY_ARCHIVE"
database_id = "b10566be-ebb1-414c-beab-eac03f1a909b"

[[d1_databases]]
binding = "DB_AUDIT"
database_name = "SMART_ODPADY_AUDIT"
database_id = "5abc8fa4-c155-4bf0-9c46-2db73d6d98e0"

[[r2_buckets]]
binding = "R2_ARCHIVE"
bucket_name = "smart-odpady-archive"

[triggers]
crons = ["*/5 * * * *"]
