const CONTACT_IMPORTED_AT = "2026-06-22T00:00:00.000Z";

// Contacts imported from Contact.xlsx on 2026-06-22.
export const CONTACT_USERS = [
  {
    id: "radim-oplustil",
    name: "Radim Opluštil",
    email: "oplustil@kaiserservis.cz",
    phone: "604 542 004",
    role: "admin",
    status: "active",
    department: "Vedení společnosti",
    position: "Jednatel společnosti",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "petr-lichtenberg",
    name: "Petr Lichtenberg",
    email: "lichtenberg@kaiserservis.cz",
    phone: "731 192 810",
    role: "ridic",
    status: "active",
    department: "Provoz",
    position: "Řidič",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "alena-curikova",
    name: "Alena Čuříková",
    email: "curikova@kaiserservis.cz",
    phone: "731 667 439",
    role: "kancelar",
    status: "active",
    department: "Evidence odpadů",
    position: "Vedoucí evidence odpadů",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "milan-gazi",
    name: "Milan Gaží",
    email: "gazi@kaiserservis.cz",
    phone: "603 210 961",
    role: "management",
    status: "active",
    department: "Vedení společnosti",
    position: "Jednatel společnosti",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "marcela-oplustilova",
    name: "Marcela Opluštilová",
    email: "kancelar@kaiserservis.cz",
    phone: "734 524 415",
    role: "kancelar",
    status: "active",
    department: "Finanční oddělení",
    position: "Vydané faktury",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "lucie-jezkova",
    name: "Lucie Lichtenbergová",
    email: "jezkova@kaiserservis.cz",
    phone: "731 640 488",
    role: "kancelar",
    status: "active",
    department: "Kancelář",
    position: "Vedoucí kanceláře",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "alena-trneckova",
    name: "Alena Trnečková",
    email: "trneckova@kaiserservis.cz",
    phone: "731 541 656",
    role: "readonly",
    status: "active",
    department: "Legislativa",
    position: "Legislativní poradce",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "lenka-kourilova",
    name: "Lenka Kouřilová",
    email: "lenka@kaiserservis.cz",
    phone: "739 575 871",
    role: "management",
    status: "active",
    department: "Vedení firmy",
    position: "Vedení firmy",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-bronislav-ondrasek",
    name: "Bronislav Ondrášek",
    email: "bronislav.ondrasek@seznam.cz",
    phone: "736 649 120",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / ROP",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null,
    modules: []
  },
  {
    id: "dominik-pistacek",
    name: "Dominik Pišťáček",
    email: "pistacek@kaiserservis.cz",
    phone: "605 222 760",
    role: "ridic",
    status: "active",
    department: "Provoz",
    position: "Řidič",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "tomas-gazi",
    name: "Tomáš Gaží",
    email: "dispecer@kaiserservis.cz",
    phone: "605 309 812",
    role: "management",
    status: "active",
    department: "Vedení firmy",
    position: "Vedení firmy",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "patrik-cepelak",
    name: "Patrik Čepelák",
    email: "cepelak@kaiserservis.cz",
    phone: "731 566 803",
    role: "ridic",
    status: "active",
    department: "Provoz",
    position: "Řidič",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-jan-gazi",
    name: "Jan Gaží",
    email: "jan.gazi@kaiser.local",
    phone: "732 815 589",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / LJE",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null,
    modules: []
  },
  {
    id: "patrik-istvanek",
    name: "Patrik Ištvánek",
    email: "",
    phone: "731 641 474",
    role: "ridic",
    status: "active",
    department: "Provoz",
    position: "Řidič",
    permissions: [
      { moduleId: "driver-reports", action: "view", allowed: true },
      { moduleId: "driver-reports", action: "edit", allowed: true },
      { moduleId: "driver-reports", action: "manage", allowed: true }
    ],
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-martin-istvanek",
    name: "Martin Ištvánek",
    email: "martin.istvanek@kaiser.local",
    phone: "731 420 380",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / LJE",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null,
    modules: []
  },
  {
    id: "pneumatiky-radek-pich",
    name: "Radek Pich",
    email: "radek.pich@kaiser.local",
    phone: "728 504 881",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / JOL, ROP",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null,
    modules: []
  },
  {
    id: "pneumatiky-ondrej-hanzlicek",
    name: "Ondřej Hanzlíček",
    email: "ondrej.hanzlicek@kaiser.local",
    phone: "736 168 405",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / LJE",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null,
    modules: []
  },
  {
    id: "pneumatiky-martin-pinkava",
    name: "Martin Pinkava",
    email: "martin.pinkava@kaiser.local",
    phone: "731 636 880",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / JOL",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null,
    modules: []
  },
  {
    id: "pneumatiky-roman-drdlik",
    name: "Roman Drdlík",
    email: "roman.drdlik@kaiser.local",
    phone: "731 420 379",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / ROP, PIU",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null,
    modules: []
  },
  {
    id: "pneumatiky-jakub-kozlicek",
    name: "Jakub Kozlíček",
    email: "jakub.kozlicek@kaiser.local",
    phone: "734 528 650",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / LJE",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null,
    modules: []
  },
  {
    id: "pneumatiky-stanislav-janecek",
    name: "Stanislav Janeček",
    email: "stanislav.janecek@kaiser.local",
    phone: "604 363 492",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / JOL",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null,
    modules: []
  },
  {
    id: "pneumatiky-martin-bartos",
    name: "Martin Bartoš",
    email: "martin.bartos@kaiser.local",
    phone: "605 203 296",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / JOL, ROP",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null,
    modules: []
  },
  {
    id: "pneumatiky-petr-kucera",
    name: "Petr Kučera",
    email: "petr.kucera@kaiser.local",
    phone: "773 591 562",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / JOL",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null,
    modules: []
  },
  {
    id: "jiri-hrebicek",
    name: "Jiří Hřebíček",
    email: "",
    phone: "777 988 359",
    role: "ridic",
    status: "active",
    department: "Provoz",
    position: "Řidič",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "andrej-novak",
    name: "Andrej Novák",
    email: "",
    phone: "721 195 595",
    role: "ridic",
    status: "active",
    department: "Provoz",
    position: "Řidič",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "libor-vodicka",
    name: "Libor Vodička",
    email: "",
    phone: "607 569 492",
    role: "ridic",
    status: "active",
    department: "Provoz",
    position: "Řidič",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "kristyna-gaziova",
    name: "Kristýna Gažíová",
    email: "kristyna.gaziova@kaiserservis.cz",
    phone: "722 962 832",
    role: "ridic",
    status: "active",
    department: "Provoz",
    position: "Řidič",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-jan-kovarik",
    name: "Jan Kovařík",
    email: "jan.kovarik@kaiser.local",
    phone: "774 661 032",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / ROP",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null,
    modules: []
  },
  {
    id: "jarmila-olsanikova",
    name: "Jarmila Olšaníková",
    email: "olsanikova@kaiserservis.cz",
    phone: "603 565 449",
    role: "readonly",
    status: "active",
    department: "Asistence jednatelů",
    position: "Asistentka jednatelů",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "marketa-pernicova",
    name: "Markéta Pernicová",
    email: "marketa.oplustilova@kaiserservis.cz",
    phone: "606 054 688",
    role: "kancelar",
    status: "active",
    department: "Finanční oddělení",
    position: "Přijaté faktury",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "lenka-dlouha",
    name: "Lenka Dlouhá",
    email: "dlouha@kaiserservis.cz",
    phone: "731 623 963",
    role: "readonly",
    status: "active",
    department: "Laboratoř",
    position: "Provozní laborantka",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "silvie-kupcikova",
    name: "Silvie Kupčíková",
    email: "kupcikova@kaiserservis.cz",
    phone: "774 942 434",
    role: "readonly",
    status: "active",
    department: "Evidence odpadů",
    position: "Evidence odpadů",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "martin-holas",
    name: "Martin Holas",
    email: "",
    phone: "735 795 518",
    role: "ridic",
    status: "active",
    department: "Provoz",
    position: "Řidič",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-milan-popelar",
    name: "Milan Popelár",
    email: "milan.popelar@kaiser.local",
    phone: "725 411 605",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / JOL",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null,
    modules: []
  },
  {
    id: "pneumatiky-miroslav-vasek",
    name: "Miroslav Vašek",
    preferredVocative: "Mirku",
    email: "miroslav.vasek@kaiser.local",
    phone: "735 795 517",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / PIU",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null,
    modules: []
  },
  {
    id: "ulyana-bartosova",
    name: "Ulyana Bartošová",
    email: "bartosova@kaiserservis.cz",
    phone: "605 427 741",
    role: "dispecer",
    status: "active",
    department: "Dispečink",
    position: "Dispečerka",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-martin-bravenec",
    name: "Martin Bravenec",
    email: "martin.bravenec@kaiser.local",
    phone: "727 952 990",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / LJE",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null,
    modules: []
  },
  {
    id: "pneumatiky-martin-macejka",
    name: "Martin Macejka",
    email: "martin.macejka@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / ROP",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null,
    modules: []
  },
  {
    id: "marek-pernica",
    name: "Marek Pernica",
    email: "pernica@kaiserservis.cz",
    phone: "547 213 000",
    role: "ridic",
    status: "active",
    department: "Provoz",
    position: "Řidič",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "jiri-sovka",
    name: "Jiří Sovka",
    email: "",
    phone: "606 033 141",
    role: "ridic",
    status: "active",
    department: "Provoz",
    position: "Řidič",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "jakub-hrbacek",
    name: "Jakub Hrbáček",
    email: "",
    phone: "608 109 712",
    role: "ridic",
    status: "active",
    department: "Provoz",
    position: "Řidič",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "simona-sefcikova",
    name: "Simona Šefčíková",
    email: "simona@kaiserservis.cz",
    phone: "739 376 118",
    role: "dispecer",
    status: "active",
    department: "Dispečink",
    position: "Dispečerka",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "david-lyznar",
    name: "David Lyznar",
    email: "",
    phone: "601 262 666",
    role: "ridic",
    status: "active",
    department: "Provoz",
    position: "Řidič",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "jaromir-pecuch",
    name: "Jaromír Pecůch",
    email: "jarapecuch@kaiserservis.cz",
    phone: "604 462 499",
    role: "ridic",
    status: "active",
    department: "Provoz",
    position: "Řidič",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-jan-kozumplik",
    name: "Jan Kozumplík",
    email: "jan.kozumplik@kaiser.local",
    phone: "721 303 212",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / LJE",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null,
    modules: []
  },
  {
    id: "petr-janosek",
    name: "Petr Janošek",
    email: "janosek@kaiserservis.cz",
    phone: "793 950 864",
    role: "ridic",
    status: "active",
    department: "Provoz",
    position: "Řidič",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-stefan-brychnac",
    name: "Štefan Brychnáč",
    email: "stefan.brychnac@kaiser.local",
    phone: "608 456 022",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / ROP",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null,
    modules: []
  },
  {
    id: "petra-istvanek",
    name: "Petra Ištvánek",
    email: "petra@kaiserservis.cz",
    phone: "606 213 943",
    role: "ridic",
    status: "active",
    department: "Provoz",
    position: "Řidič",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-libor-ferbar",
    name: "Libor Ferbar",
    email: "libor.ferbar@kaiser.local",
    phone: "737 476 043",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / ROP",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null,
    modules: []
  },
  {
    id: "pneumatiky-david-urc",
    name: "David Urc",
    email: "david.urc@kaiser.local",
    phone: "777 599 056",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / PIU",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null,
    modules: []
  },
  {
    id: "petr-pancl",
    name: "Petr Pancl",
    email: "pancl@kaiserservis.cz",
    phone: "739 376 257",
    role: "ridic",
    status: "active",
    department: "Provoz",
    position: "Řidič",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-miroslav-florian",
    name: "Miroslav Florián",
    email: "miroslav.florian@kaiser.local",
    phone: "777 103 504",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / ROP",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null,
    modules: []
  },
  {
    id: "pneumatiky-lukas-malanik",
    name: "Lukáš Malánik",
    email: "lukas.malanik@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / PIU",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null,
    modules: []
  },
  {
    id: "andrea-hegrova",
    name: "Andrea Hegrová",
    email: "andrea@kaiserservis.cz",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Provoz",
    position: "Řidič",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  },
  {
    id: "miloslav-gahut",
    name: "Miloslav Gahut",
    email: "",
    phone: "725 722 477",
    role: "ridic",
    status: "active",
    department: "Provoz",
    position: "Řidič",
    createdAt: CONTACT_IMPORTED_AT,
    lastLoginAt: null
  }
];
