const CREATED_AT = "2026-06-22T00:00:00.000Z";

// Public contacts imported from https://www.kaiserservis.cz/kontakty/.
export const DEFAULT_USERS = [
  {
    id: "radim-oplustil",
    name: "Radim Opluštil",
    email: "oplustil@kaiserservis.cz",
    phone: "604 542 004",
    role: "admin",
    status: "active",
    department: "Vedení společnosti",
    position: "Jednatel společnosti",
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "martin-konecek",
    name: "Martin Koneček",
    email: "martin.konecek@gmail.com",
    phone: "777 204 462",
    role: "admin",
    status: "active",
    department: "Administrace systému",
    position: "Admin",
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "milan-gazi",
    name: "Milan Gaží",
    email: "gazi@kaiserservis.cz",
    phone: "",
    role: "management",
    status: "active",
    department: "Vedení společnosti",
    position: "Jednatel společnosti",
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "tomas-gazi",
    name: "Tomáš Gaží",
    email: "tomas.gazi@kaiserservis.cz",
    phone: "605 309 812",
    role: "management",
    status: "active",
    department: "Vedení firmy",
    position: "Vedení firmy",
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "lenka-kourilova",
    name: "Lenka Kouřilová",
    email: "kourilova@kaiserservis.cz",
    phone: "739 575 871",
    role: "management",
    status: "active",
    department: "Vedení firmy",
    position: "Vedení firmy",
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "marcela-oplustilova",
    name: "Marcela Opluštilová",
    email: "kancelar@kaiserservis.cz",
    phone: "734 524 415",
    role: "kancelar",
    status: "active",
    department: "Finanční oddělení",
    position: "Vydané faktury",
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "lucie-jezkova",
    name: "Bc. Lucie Ježková, DiS.",
    email: "jezkova@kaiserservis.cz",
    phone: "731 640 488",
    role: "kancelar",
    status: "active",
    department: "Kancelář",
    position: "Vedoucí kanceláře",
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "alena-curikova",
    name: "Alena Čuříková",
    email: "curikova@kaiserservis.cz",
    phone: "731 667 439",
    role: "kancelar",
    status: "active",
    department: "Evidence odpadů",
    position: "Vedoucí evidence odpadů",
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "alena-trneckova",
    name: "Ing. Alena Trnečková",
    email: "trneckova@kaiserservis.cz",
    phone: "731 541 656",
    role: "readonly",
    status: "active",
    department: "Legislativa",
    position: "Legislativní poradce",
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "jarmila-olsanikova",
    name: "Jarmila Olšaníková",
    email: "olsanikova@kaiserservis.cz",
    phone: "603 565 449",
    role: "readonly",
    status: "active",
    department: "Asistence jednatelů",
    position: "Asistentka jednatelů",
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "lenka-dlouha",
    name: "Lenka Dlouhá",
    email: "dlouha@kaiserservis.cz",
    phone: "731 623 963",
    role: "readonly",
    status: "active",
    department: "Laboratoř",
    position: "Provozní laborantka",
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "ulyana-bartosova",
    name: "Ulyana Bartošová",
    email: "bartosova@kaiserservis.cz",
    phone: "605 427 741",
    role: "dispecer",
    status: "active",
    department: "Dispečink",
    position: "Dispečerka",
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "marketa-pernicova",
    name: "Markéta Pernicová",
    email: "marketa.oplustilova@kaiserservis.cz",
    phone: "606 054 688",
    role: "kancelar",
    status: "active",
    department: "Finanční oddělení",
    position: "Přijaté faktury",
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "simona-sefcikova",
    name: "Simona Šefčíková",
    email: "simona@kaiserservis.cz",
    phone: "739 376 118",
    role: "dispecer",
    status: "active",
    department: "Dispečink",
    position: "Dispečerka",
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "silvie-kupcikova",
    name: "Silvie Kupčíková",
    email: "kupcikova@kaiserservis.cz",
    phone: "774 942 434",
    role: "readonly",
    status: "active",
    department: "Evidence odpadů",
    position: "Evidence odpadů",
    createdAt: CREATED_AT,
    lastLoginAt: null
  },

  // Users imported from the finished Pneumatiky module. They keep Pneumatiky access and can use Dovolená / Nemoc.
  {
    id: "pneumatiky-dilna",
    name: "Vedoucí dílny",
    email: "dilna@kaiserservis.cz",
    phone: "",
    role: "garazmistr",
    status: "active",
    department: "Pneumatiky",
    position: "Dílna / Brno",
    modules: ["tyres", "absence"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-management",
    name: "Management",
    email: "management@kaiserservis.cz",
    phone: "",
    role: "management",
    status: "active",
    department: "Pneumatiky",
    position: "Management / Šlapanice",
    modules: ["tyres", "absence"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-bronislav-ondrasek",
    name: "Bronislav Ondrášek",
    email: "bronislav.ondrasek@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / ROP",
    modules: ["tyres", "absence", "vehicle-tracking"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-david-urc",
    name: "David Urc",
    email: "david.urc@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / PIU",
    modules: ["tyres", "absence", "vehicle-tracking"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-jakub-kozlicek",
    name: "Jakub Kozlíček",
    email: "jakub.kozlicek@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / LJE",
    modules: ["tyres", "absence", "vehicle-tracking"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-jan-gazi",
    name: "Jan Gaží",
    email: "jan.gazi@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / LJE",
    modules: ["tyres", "absence", "vehicle-tracking"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-jan-kovarik",
    name: "Jan Kovařík",
    email: "jan.kovarik@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / ROP",
    modules: ["tyres", "absence", "vehicle-tracking"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-jan-kozumplik",
    name: "Jan Kozumplík",
    email: "jan.kozumplik@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / LJE",
    modules: ["tyres", "absence", "vehicle-tracking"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-libor-ferbar",
    name: "Libor Ferbar",
    email: "libor.ferbar@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / ROP",
    modules: ["tyres", "absence", "vehicle-tracking"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-lukas-malanik",
    name: "Lukáš Malánik",
    email: "lukas.malanik@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / PIU",
    modules: ["tyres", "absence", "vehicle-tracking"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-martin-bartos",
    name: "Martin Bartoš",
    email: "martin.bartos@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / JOL, ROP",
    modules: ["tyres", "absence", "vehicle-tracking"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-martin-bravenec",
    name: "Martin Bravenec",
    email: "martin.bravenec@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / LJE",
    modules: ["tyres", "absence", "vehicle-tracking"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-martin-istvanek",
    name: "Martin Ištvánek",
    email: "martin.istvanek@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / LJE",
    modules: ["tyres", "absence", "vehicle-tracking"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-martin-macejka",
    name: "Martin Macejka",
    email: "martin.macejka@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / ROP",
    modules: ["tyres", "absence", "vehicle-tracking"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-martin-pinkava",
    name: "Martin Pinkava",
    email: "martin.pinkava@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / JOL",
    modules: ["tyres", "absence", "vehicle-tracking"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-milan-popelar",
    name: "Milan Popelár",
    email: "milan.popelar@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / JOL",
    modules: ["tyres", "absence", "vehicle-tracking"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-miroslav-florian",
    name: "Miroslav Florián",
    email: "miroslav.florian@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / ROP",
    modules: ["tyres", "absence", "vehicle-tracking"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-miroslav-vasek",
    name: "Miroslav Vašek",
    preferredVocative: "Mirku",
    email: "miroslav.vasek@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / PIU",
    modules: ["tyres", "absence", "vehicle-tracking"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-ondrej-hanzlicek",
    name: "Ondřej Hanzlíček",
    email: "ondrej.hanzlicek@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / LJE",
    modules: ["tyres", "absence", "vehicle-tracking"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-petr-kucera",
    name: "Petr Kučera",
    email: "petr.kucera@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / JOL",
    modules: ["tyres", "absence", "vehicle-tracking"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-radek-pich",
    name: "Radek Pich",
    email: "radek.pich@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / JOL, ROP",
    modules: ["tyres", "absence", "vehicle-tracking"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-roman-drdlik",
    name: "Roman Drdlík",
    email: "roman.drdlik@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / ROP, PIU",
    modules: ["tyres", "absence", "vehicle-tracking"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-stanislav-janecek",
    name: "Stanislav Janeček",
    email: "stanislav.janecek@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / JOL",
    modules: ["tyres", "absence", "vehicle-tracking"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  },
  {
    id: "pneumatiky-stefan-brychnac",
    name: "Štefan Brychnáč",
    email: "stefan.brychnac@kaiser.local",
    phone: "",
    role: "ridic",
    status: "active",
    department: "Pneumatiky",
    position: "Řidič / ROP",
    modules: ["tyres", "absence", "vehicle-tracking"],
    createdAt: CREATED_AT,
    lastLoginAt: null
  }
];
