INSERT OR IGNORE INTO module_rules (
  id,
  module_key,
  title,
  description,
  type,
  status,
  conditions_json,
  actions_json,
  is_automation,
  trigger_type,
  schedule_cron,
  event_name,
  cloud_runner,
  created_by_user_id,
  created_at,
  updated_by_user_id,
  updated_at
) VALUES
  (
    'rcs-sms-autopilot-twilio-signature',
    'rcs-sms-autopilot',
    'Ověření Twilio webhooku',
    'Každá příchozí RCS/SMS odpověď musí mít platný Twilio podpis nebo schválený serverový webhook secret.',
    'rule',
    'active',
    '{"source":"twilio","signatureRequired":true}',
    '{"onFailure":"reject_without_processing"}',
    0,
    'webhook',
    NULL,
    'twilio_inbound',
    'functions/_lib/twilio-webhook-auth.js',
    'system',
    CURRENT_TIMESTAMP,
    'system',
    CURRENT_TIMESTAMP
  ),
  (
    'rcs-sms-autopilot-fixed-rules',
    'rcs-sms-autopilot',
    'STOP, duplicity a bezpečnost před AI',
    'STOP, prázdné zprávy, duplicity, blokované kontakty a bezprostřední nebezpečí se zpracují před OpenAI.',
    'rule',
    'active',
    '{"beforeOpenAI":true}',
    '{"stop":"unsubscribe","duplicate":"ignore","danger":"human_takeover"}',
    0,
    'event',
    NULL,
    'rcs_sms_received',
    'functions/api/twilio/inbound.js',
    'system',
    CURRENT_TIMESTAMP,
    'system',
    CURRENT_TIMESTAMP
  ),
  (
    'rcs-sms-autopilot-async-processing',
    'rcs-sms-autopilot',
    'Asynchronní zpracování příchozí odpovědi',
    'Webhook zprávu nejdřív idempotentně uloží a další práci předá serverovému waitUntil.',
    'automation',
    'inactive',
    '{"mode":"live","requiresStoredInbound":true}',
    '{"process":"classify_validate_execute_reply"}',
    1,
    'webhook',
    NULL,
    'rcs_sms_received',
    'Cloudflare Pages Functions waitUntil',
    'system',
    CURRENT_TIMESTAMP,
    'system',
    CURRENT_TIMESTAMP
  ),
  (
    'rcs-sms-autopilot-retry-runner',
    'rcs-sms-autopilot',
    'Obnova nedokončeného zpracování',
    'Cloudový runner obnoví pouze uložené zprávy čekající na zpracování a používá idempotentní nástroje.',
    'automation',
    'inactive',
    '{"mode":"live","maxAttempts":3}',
    '{"retry":"received_or_failed_messages"}',
    1,
    'time',
    '*/5 * * * *',
    NULL,
    'kaiser-module-automation-runner',
    'system',
    CURRENT_TIMESTAMP,
    'system',
    CURRENT_TIMESTAMP
  );
